// Auto-generated by generate_demo_snapshot.py - do not edit by hand.
const DEMO_DATA = {
  "generated_note": "Precomputed snapshot from the synthetic dataset for offline/standalone demo use.",
  "stats": {
    "total_transactions": 96979,
    "flagged_medium_plus": 498,
    "flagged_high": 465,
    "mule_wallets_detected": 12,
    "suspicious_clusters": 3,
    "model_evaluation": {
      "test_set_size": 24245,
      "test_set_positives": 126,
      "roc_auc": 0.9955,
      "average_precision": 0.9417,
      "threshold_0.5": {
        "precision": 0.9478,
        "recall": 0.8651,
        "f1": 0.9046
      },
      "threshold_0.7_high_risk": {
        "precision": 0.9727,
        "recall": 0.8492
      },
      "confusion_matrix": {
        "labels": [
          "actual_normal",
          "actual_scam"
        ],
        "columns": [
          "pred_normal",
          "pred_scam"
        ],
        "matrix": [
          [
            24113,
            6
          ],
          [
            17,
            109
          ]
        ]
      }
    },
    "feature_importance": {
      "amount_vs_avg_ratio": 0.42584934379409645,
      "amount_zscore": 0.19713679606877382,
      "sender_velocity_10min": 0.13220196936127884,
      "receiver_age_days": 0.12349164786791916,
      "new_device_for_sender": 0.030094815195903728,
      "amount": 0.02772426650147319,
      "unusual_hour": 0.02733062780952477,
      "receiver_indegree_1h": 0.02503315282997786,
      "receiver_fanout_30min": 0.010958729433570711,
      "is_new_recipient": 0.00017865113748135312
    }
  },
  "transactions": [
    {
      "txn_id": "T0096886",
      "timestamp": "2026-09-14 12:00:00",
      "sender_id": "U01849",
      "receiver_id": "M720ea9",
      "channel": "send_money",
      "amount": 3896.32,
      "sender_district": "Rajshahi",
      "risk_score": 1.0,
      "risk_level": "high",
      "features": {
        "amount": 3896.32,
        "is_new_recipient": 1.0,
        "amount_vs_avg_ratio": 5.318130113104768,
        "amount_zscore": 11.373402354510985,
        "unusual_hour": 0.0,
        "sender_velocity_10min": 0.0,
        "new_device_for_sender": 1.0,
        "receiver_age_days": 0.0,
        "receiver_indegree_1h": 0.0,
        "receiver_fanout_30min": 0.0
      },
      "scam_type_actual": "account_takeover",
      "ai_case_summary": {
        "risk_level": "HIGH",
        "scam_type_guess": "social_engineering",
        "summary": "Transaction T0096886 flagged as HIGH RISK (score 100%), most consistent with a scam-call style transfer (large, one-off payment to a brand-new recipient). Evidence: the sender has never sent money to this recipient before; the amount is 5.3x the sender's usual transfer size; it came from a device not previously associated with this sender; the receiving wallet has no transaction history before this. Recommend holding this transaction for manual review before release.",
        "recommendation": "Recommend holding this transaction for manual review before release.",
        "evidence_used": {
          "features": {
            "amount": 3896.32,
            "is_new_recipient": 1.0,
            "amount_vs_avg_ratio": 5.318130113104768,
            "amount_zscore": 11.373402354510985,
            "unusual_hour": 0.0,
            "sender_velocity_10min": 0.0,
            "new_device_for_sender": 1.0,
            "receiver_age_days": 0.0,
            "receiver_indegree_1h": 0.0,
            "receiver_fanout_30min": 0.0
          },
          "mule_evidence": null
        }
      },
      "mule_network_evidence": null
    },
    {
      "txn_id": "T0096642",
      "timestamp": "2026-09-02 20:20:00",
      "sender_id": "U00218",
      "receiver_id": "M8f3e6c",
      "channel": "send_money",
      "amount": 4000.52,
      "sender_district": "Dhaka",
      "risk_score": 1.0,
      "risk_level": "high",
      "features": {
        "amount": 4000.52,
        "is_new_recipient": 1.0,
        "amount_vs_avg_ratio": 5.324664937585494,
        "amount_zscore": 11.662293675701276,
        "unusual_hour": 0.0,
        "sender_velocity_10min": 0.0,
        "new_device_for_sender": 0.0,
        "receiver_age_days": 0.0,
        "receiver_indegree_1h": 2.0,
        "receiver_fanout_30min": 0.0
      },
      "scam_type_actual": "mule_ring",
      "ai_case_summary": {
        "risk_level": "HIGH",
        "scam_type_guess": "social_engineering",
        "summary": "Transaction T0096642 flagged as HIGH RISK (score 100%), most consistent with a scam-call style transfer (large, one-off payment to a brand-new recipient). Evidence: the sender has never sent money to this recipient before; the amount is 5.3x the sender's usual transfer size; the receiving wallet has no transaction history before this. Recommend holding this transaction for manual review before release.",
        "recommendation": "Recommend holding this transaction for manual review before release.",
        "evidence_used": {
          "features": {
            "amount": 4000.52,
            "is_new_recipient": 1.0,
            "amount_vs_avg_ratio": 5.324664937585494,
            "amount_zscore": 11.662293675701276,
            "unusual_hour": 0.0,
            "sender_velocity_10min": 0.0,
            "new_device_for_sender": 0.0,
            "receiver_age_days": 0.0,
            "receiver_indegree_1h": 2.0,
            "receiver_fanout_30min": 0.0
          },
          "mule_evidence": null
        }
      },
      "mule_network_evidence": null
    },
    {
      "txn_id": "T0024258",
      "timestamp": "2026-08-15 16:36:00",
      "sender_id": "A0063",
      "receiver_id": "U01949",
      "channel": "cash_in",
      "amount": 5165.43,
      "sender_district": "Khulna",
      "risk_score": 1.0,
      "risk_level": "high",
      "features": {
        "amount": 5165.43,
        "is_new_recipient": 1.0,
        "amount_vs_avg_ratio": 5.32860521313936,
        "amount_zscore": 5.397517962109502,
        "unusual_hour": 0.0,
        "sender_velocity_10min": 0.0,
        "new_device_for_sender": 1.0,
        "receiver_age_days": 2.0,
        "receiver_indegree_1h": 0.0,
        "receiver_fanout_30min": 1.0
      },
      "scam_type_actual": "none",
      "ai_case_summary": {
        "risk_level": "HIGH",
        "scam_type_guess": "social_engineering",
        "summary": "Transaction T0024258 flagged as HIGH RISK (score 100%), most consistent with a scam-call style transfer (large, one-off payment to a brand-new recipient). Evidence: the sender has never sent money to this recipient before; the amount is 5.3x the sender's usual transfer size; it came from a device not previously associated with this sender. Recommend holding this transaction for manual review before release.",
        "recommendation": "Recommend holding this transaction for manual review before release.",
        "evidence_used": {
          "features": {
            "amount": 5165.43,
            "is_new_recipient": 1.0,
            "amount_vs_avg_ratio": 5.32860521313936,
            "amount_zscore": 5.397517962109502,
            "unusual_hour": 0.0,
            "sender_velocity_10min": 0.0,
            "new_device_for_sender": 1.0,
            "receiver_age_days": 2.0,
            "receiver_indegree_1h": 0.0,
            "receiver_fanout_30min": 1.0
          },
          "mule_evidence": null
        }
      },
      "mule_network_evidence": null
    },
    {
      "txn_id": "T0045729",
      "timestamp": "2026-08-29 07:12:00",
      "sender_id": "A0104",
      "receiver_id": "U00611",
      "channel": "cash_in",
      "amount": 5252.7,
      "sender_district": "Barishal",
      "risk_score": 1.0,
      "risk_level": "high",
      "features": {
        "amount": 5252.7,
        "is_new_recipient": 1.0,
        "amount_vs_avg_ratio": 5.331764997034598,
        "amount_zscore": 4.609025245561435,
        "unusual_hour": 0.0,
        "sender_velocity_10min": 1.0,
        "new_device_for_sender": 1.0,
        "receiver_age_days": 2.0,
        "receiver_indegree_1h": 0.0,
        "receiver_fanout_30min": 0.0
      },
      "scam_type_actual": "none",
      "ai_case_summary": {
        "risk_level": "HIGH",
        "scam_type_guess": "social_engineering",
        "summary": "Transaction T0045729 flagged as HIGH RISK (score 100%), most consistent with a scam-call style transfer (large, one-off payment to a brand-new recipient). Evidence: the sender has never sent money to this recipient before; the amount is 5.3x the sender's usual transfer size; it came from a device not previously associated with this sender. Recommend holding this transaction for manual review before release.",
        "recommendation": "Recommend holding this transaction for manual review before release.",
        "evidence_used": {
          "features": {
            "amount": 5252.7,
            "is_new_recipient": 1.0,
            "amount_vs_avg_ratio": 5.331764997034598,
            "amount_zscore": 4.609025245561435,
            "unusual_hour": 0.0,
            "sender_velocity_10min": 1.0,
            "new_device_for_sender": 1.0,
            "receiver_age_days": 2.0,
            "receiver_indegree_1h": 0.0,
            "receiver_fanout_30min": 0.0
          },
          "mule_evidence": null
        }
      },
      "mule_network_evidence": null
    },
    {
      "txn_id": "T0075405",
      "timestamp": "2026-09-16 13:32:00",
      "sender_id": "A0105",
      "receiver_id": "U01901",
      "channel": "cash_in",
      "amount": 6346.5,
      "sender_district": "Barishal",
      "risk_score": 1.0,
      "risk_level": "high",
      "features": {
        "amount": 6346.5,
        "is_new_recipient": 1.0,
        "amount_vs_avg_ratio": 5.322613278857117,
        "amount_zscore": 3.677461293622182,
        "unusual_hour": 0.0,
        "sender_velocity_10min": 0.0,
        "new_device_for_sender": 1.0,
        "receiver_age_days": 3.0,
        "receiver_indegree_1h": 0.0,
        "receiver_fanout_30min": 0.0
      },
      "scam_type_actual": "none",
      "ai_case_summary": {
        "risk_level": "HIGH",
        "scam_type_guess": "social_engineering",
        "summary": "Transaction T0075405 flagged as HIGH RISK (score 100%), most consistent with a scam-call style transfer (large, one-off payment to a brand-new recipient). Evidence: the sender has never sent money to this recipient before; the amount is 5.3x the sender's usual transfer size; it came from a device not previously associated with this sender. Recommend holding this transaction for manual review before release.",
        "recommendation": "Recommend holding this transaction for manual review before release.",
        "evidence_used": {
          "features": {
            "amount": 6346.5,
            "is_new_recipient": 1.0,
            "amount_vs_avg_ratio": 5.322613278857117,
            "amount_zscore": 3.677461293622182,
            "unusual_hour": 0.0,
            "sender_velocity_10min": 0.0,
            "new_device_for_sender": 1.0,
            "receiver_age_days": 3.0,
            "receiver_indegree_1h": 0.0,
            "receiver_fanout_30min": 0.0
          },
          "mule_evidence": null
        }
      },
      "mule_network_evidence": null
    },
    {
      "txn_id": "T0096601",
      "timestamp": "2026-09-22 22:05:00",
      "sender_id": "U01247",
      "receiver_id": "M2e6ecd",
      "channel": "send_money",
      "amount": 4748.48,
      "sender_district": "Barishal",
      "risk_score": 1.0,
      "risk_level": "high",
      "features": {
        "amount": 4748.48,
        "is_new_recipient": 1.0,
        "amount_vs_avg_ratio": 5.310110271060986,
        "amount_zscore": 6.762836450913756,
        "unusual_hour": 0.0,
        "sender_velocity_10min": 0.0,
        "new_device_for_sender": 0.0,
        "receiver_age_days": 1.0,
        "receiver_indegree_1h": 0.0,
        "receiver_fanout_30min": 0.0
      },
      "scam_type_actual": "social_engineering",
      "ai_case_summary": {
        "risk_level": "HIGH",
        "scam_type_guess": "social_engineering",
        "summary": "Transaction T0096601 flagged as HIGH RISK (score 100%), most consistent with a scam-call style transfer (large, one-off payment to a brand-new recipient). Evidence: the sender has never sent money to this recipient before; the amount is 5.3x the sender's usual transfer size; the receiving wallet has no transaction history before this. Recommend holding this transaction for manual review before release.",
        "recommendation": "Recommend holding this transaction for manual review before release.",
        "evidence_used": {
          "features": {
            "amount": 4748.48,
            "is_new_recipient": 1.0,
            "amount_vs_avg_ratio": 5.310110271060986,
            "amount_zscore": 6.762836450913756,
            "unusual_hour": 0.0,
            "sender_velocity_10min": 0.0,
            "new_device_for_sender": 0.0,
            "receiver_age_days": 1.0,
            "receiver_indegree_1h": 0.0,
            "receiver_fanout_30min": 0.0
          },
          "mule_evidence": null
        }
      },
      "mule_network_evidence": null
    },
    {
      "txn_id": "T0096939",
      "timestamp": "2026-09-10 03:01:00",
      "sender_id": "U01366",
      "receiver_id": "M71c3f6",
      "channel": "send_money",
      "amount": 8091.49,
      "sender_district": "Narayanganj",
      "risk_score": 0.9999999999643996,
      "risk_level": "high",
      "features": {
        "amount": 8091.49,
        "is_new_recipient": 1.0,
        "amount_vs_avg_ratio": 3.481415522109891,
        "amount_zscore": 1.893517563289768,
        "unusual_hour": 1.0,
        "sender_velocity_10min": 1.0,
        "new_device_for_sender": 0.0,
        "receiver_age_days": 0.0,
        "receiver_indegree_1h": 0.0,
        "receiver_fanout_30min": 0.0
      },
      "scam_type_actual": "account_takeover",
      "ai_case_summary": {
        "risk_level": "HIGH",
        "scam_type_guess": "social_engineering",
        "summary": "Transaction T0096939 flagged as HIGH RISK (score 100%), most consistent with a scam-call style transfer (large, one-off payment to a brand-new recipient). Evidence: the sender has never sent money to this recipient before; the amount is 3.5x the sender's usual transfer size; it happened late at night (11pm-5am), outside typical hours; the receiving wallet has no transaction history before this. Recommend holding this transaction for manual review before release.",
        "recommendation": "Recommend holding this transaction for manual review before release.",
        "evidence_used": {
          "features": {
            "amount": 8091.49,
            "is_new_recipient": 1.0,
            "amount_vs_avg_ratio": 3.481415522109891,
            "amount_zscore": 1.893517563289768,
            "unusual_hour": 1.0,
            "sender_velocity_10min": 1.0,
            "new_device_for_sender": 0.0,
            "receiver_age_days": 0.0,
            "receiver_indegree_1h": 0.0,
            "receiver_fanout_30min": 0.0
          },
          "mule_evidence": null
        }
      },
      "mule_network_evidence": null
    },
    {
      "txn_id": "T0096750",
      "timestamp": "2026-09-16 02:10:00",
      "sender_id": "U01798",
      "receiver_id": "M916237",
      "channel": "send_money",
      "amount": 29463.3,
      "sender_district": "Chattogram",
      "risk_score": 0.9999999999166248,
      "risk_level": "high",
      "features": {
        "amount": 29463.3,
        "is_new_recipient": 1.0,
        "amount_vs_avg_ratio": 3.552228064632821,
        "amount_zscore": 3.395723940510207,
        "unusual_hour": 1.0,
        "sender_velocity_10min": 4.0,
        "new_device_for_sender": 0.0,
        "receiver_age_days": 0.0,
        "receiver_indegree_1h": 0.0,
        "receiver_fanout_30min": 0.0
      },
      "scam_type_actual": "account_takeover",
      "ai_case_summary": {
        "risk_level": "HIGH",
        "scam_type_guess": "social_engineering",
        "summary": "Transaction T0096750 flagged as HIGH RISK (score 100%), most consistent with a scam-call style transfer (large, one-off payment to a brand-new recipient). Evidence: the sender has never sent money to this recipient before; the amount is 3.6x the sender's usual transfer size; it happened late at night (11pm-5am), outside typical hours; the sender made 4 other transactions in the preceding 10 minutes (rapid-fire pattern); the receiving wallet has no transaction history before this. Recommend holding this transaction for manual review before release.",
        "recommendation": "Recommend holding this transaction for manual review before release.",
        "evidence_used": {
          "features": {
            "amount": 29463.3,
            "is_new_recipient": 1.0,
            "amount_vs_avg_ratio": 3.552228064632821,
            "amount_zscore": 3.395723940510207,
            "unusual_hour": 1.0,
            "sender_velocity_10min": 4.0,
            "new_device_for_sender": 0.0,
            "receiver_age_days": 0.0,
            "receiver_indegree_1h": 0.0,
            "receiver_fanout_30min": 0.0
          },
          "mule_evidence": null
        }
      },
      "mule_network_evidence": null
    },
    {
      "txn_id": "T0096719",
      "timestamp": "2026-08-12 04:03:00",
      "sender_id": "U00557",
      "receiver_id": "M3a150f",
      "channel": "send_money",
      "amount": 12190.22,
      "sender_district": "Mymensingh",
      "risk_score": 0.9999999998787824,
      "risk_level": "high",
      "features": {
        "amount": 12190.22,
        "is_new_recipient": 1.0,
        "amount_vs_avg_ratio": 3.4252737716345245,
        "amount_zscore": 2.445210892276716,
        "unusual_hour": 1.0,
        "sender_velocity_10min": 2.0,
        "new_device_for_sender": 0.0,
        "receiver_age_days": 0.0,
        "receiver_indegree_1h": 0.0,
        "receiver_fanout_30min": 0.0
      },
      "scam_type_actual": "account_takeover",
      "ai_case_summary": {
        "risk_level": "HIGH",
        "scam_type_guess": "social_engineering",
        "summary": "Transaction T0096719 flagged as HIGH RISK (score 100%), most consistent with a scam-call style transfer (large, one-off payment to a brand-new recipient). Evidence: the sender has never sent money to this recipient before; the amount is 3.4x the sender's usual transfer size; it happened late at night (11pm-5am), outside typical hours; the sender made 2 other transactions in the preceding 10 minutes (rapid-fire pattern); the receiving wallet has no transaction history before this. Recommend holding this transaction for manual review before release.",
        "recommendation": "Recommend holding this transaction for manual review before release.",
        "evidence_used": {
          "features": {
            "amount": 12190.22,
            "is_new_recipient": 1.0,
            "amount_vs_avg_ratio": 3.4252737716345245,
            "amount_zscore": 2.445210892276716,
            "unusual_hour": 1.0,
            "sender_velocity_10min": 2.0,
            "new_device_for_sender": 0.0,
            "receiver_age_days": 0.0,
            "receiver_indegree_1h": 0.0,
            "receiver_fanout_30min": 0.0
          },
          "mule_evidence": null
        }
      },
      "mule_network_evidence": null
    },
    {
      "txn_id": "T0096852",
      "timestamp": "2026-08-21 00:08:00",
      "sender_id": "U00538",
      "receiver_id": "M43daad",
      "channel": "send_money",
      "amount": 13257.28,
      "sender_district": "Dhaka",
      "risk_score": 0.999999999603713,
      "risk_level": "high",
      "features": {
        "amount": 13257.28,
        "is_new_recipient": 1.0,
        "amount_vs_avg_ratio": 3.1046730701001497,
        "amount_zscore": 2.579234345976318,
        "unusual_hour": 1.0,
        "sender_velocity_10min": 3.0,
        "new_device_for_sender": 0.0,
        "receiver_age_days": 0.0,
        "receiver_indegree_1h": 0.0,
        "receiver_fanout_30min": 0.0
      },
      "scam_type_actual": "account_takeover",
      "ai_case_summary": {
        "risk_level": "HIGH",
        "scam_type_guess": "social_engineering",
        "summary": "Transaction T0096852 flagged as HIGH RISK (score 100%), most consistent with a scam-call style transfer (large, one-off payment to a brand-new recipient). Evidence: the sender has never sent money to this recipient before; the amount is 3.1x the sender's usual transfer size; it happened late at night (11pm-5am), outside typical hours; the sender made 3 other transactions in the preceding 10 minutes (rapid-fire pattern); the receiving wallet has no transaction history before this. Recommend holding this transaction for manual review before release.",
        "recommendation": "Recommend holding this transaction for manual review before release.",
        "evidence_used": {
          "features": {
            "amount": 13257.28,
            "is_new_recipient": 1.0,
            "amount_vs_avg_ratio": 3.1046730701001497,
            "amount_zscore": 2.579234345976318,
            "unusual_hour": 1.0,
            "sender_velocity_10min": 3.0,
            "new_device_for_sender": 0.0,
            "receiver_age_days": 0.0,
            "receiver_indegree_1h": 0.0,
            "receiver_fanout_30min": 0.0
          },
          "mule_evidence": null
        }
      },
      "mule_network_evidence": null
    },
    {
      "txn_id": "T0096746",
      "timestamp": "2026-09-16 02:03:00",
      "sender_id": "U01798",
      "receiver_id": "Mf91912",
      "channel": "send_money",
      "amount": 27008.42,
      "sender_district": "Rangpur",
      "risk_score": 0.9999999994380782,
      "risk_level": "high",
      "features": {
        "amount": 27008.42,
        "is_new_recipient": 1.0,
        "amount_vs_avg_ratio": 3.839854854053825,
        "amount_zscore": 4.042149492460951,
        "unusual_hour": 1.0,
        "sender_velocity_10min": 1.0,
        "new_device_for_sender": 0.0,
        "receiver_age_days": 0.0,
        "receiver_indegree_1h": 0.0,
        "receiver_fanout_30min": 0.0
      },
      "scam_type_actual": "account_takeover",
      "ai_case_summary": {
        "risk_level": "HIGH",
        "scam_type_guess": "social_engineering",
        "summary": "Transaction T0096746 flagged as HIGH RISK (score 100%), most consistent with a scam-call style transfer (large, one-off payment to a brand-new recipient). Evidence: the sender has never sent money to this recipient before; the amount is 3.8x the sender's usual transfer size; it happened late at night (11pm-5am), outside typical hours; the receiving wallet has no transaction history before this. Recommend holding this transaction for manual review before release.",
        "recommendation": "Recommend holding this transaction for manual review before release.",
        "evidence_used": {
          "features": {
            "amount": 27008.42,
            "is_new_recipient": 1.0,
            "amount_vs_avg_ratio": 3.839854854053825,
            "amount_zscore": 4.042149492460951,
            "unusual_hour": 1.0,
            "sender_velocity_10min": 1.0,
            "new_device_for_sender": 0.0,
            "receiver_age_days": 0.0,
            "receiver_indegree_1h": 0.0,
            "receiver_fanout_30min": 0.0
          },
          "mule_evidence": null
        }
      },
      "mule_network_evidence": null
    },
    {
      "txn_id": "T0096855",
      "timestamp": "2026-08-21 00:05:00",
      "sender_id": "U00538",
      "receiver_id": "Ma30bf5",
      "channel": "send_money",
      "amount": 13386.26,
      "sender_district": "Dhaka",
      "risk_score": 0.9999999993747593,
      "risk_level": "high",
      "features": {
        "amount": 13386.26,
        "is_new_recipient": 1.0,
        "amount_vs_avg_ratio": 3.6550899219483535,
        "amount_zscore": 3.664553665256371,
        "unusual_hour": 1.0,
        "sender_velocity_10min": 2.0,
        "new_device_for_sender": 0.0,
        "receiver_age_days": 0.0,
        "receiver_indegree_1h": 0.0,
        "receiver_fanout_30min": 0.0
      },
      "scam_type_actual": "account_takeover",
      "ai_case_summary": {
        "risk_level": "HIGH",
        "scam_type_guess": "social_engineering",
        "summary": "Transaction T0096855 flagged as HIGH RISK (score 100%), most consistent with a scam-call style transfer (large, one-off payment to a brand-new recipient). Evidence: the sender has never sent money to this recipient before; the amount is 3.7x the sender's usual transfer size; it happened late at night (11pm-5am), outside typical hours; the sender made 2 other transactions in the preceding 10 minutes (rapid-fire pattern); the receiving wallet has no transaction history before this. Recommend holding this transaction for manual review before release.",
        "recommendation": "Recommend holding this transaction for manual review before release.",
        "evidence_used": {
          "features": {
            "amount": 13386.26,
            "is_new_recipient": 1.0,
            "amount_vs_avg_ratio": 3.6550899219483535,
            "amount_zscore": 3.664553665256371,
            "unusual_hour": 1.0,
            "sender_velocity_10min": 2.0,
            "new_device_for_sender": 0.0,
            "receiver_age_days": 0.0,
            "receiver_indegree_1h": 0.0,
            "receiver_fanout_30min": 0.0
          },
          "mule_evidence": null
        }
      },
      "mule_network_evidence": null
    },
    {
      "txn_id": "T0096830",
      "timestamp": "2026-08-22 11:10:00",
      "sender_id": "U00484",
      "receiver_id": "Maa29a8",
      "channel": "send_money",
      "amount": 9392.3,
      "sender_district": "Barishal",
      "risk_score": 0.99999999937372,
      "risk_level": "high",
      "features": {
        "amount": 9392.3,
        "is_new_recipient": 1.0,
        "amount_vs_avg_ratio": 3.3693415022746147,
        "amount_zscore": 3.524019742323913,
        "unusual_hour": 0.0,
        "sender_velocity_10min": 4.0,
        "new_device_for_sender": 0.0,
        "receiver_age_days": 0.0,
        "receiver_indegree_1h": 0.0,
        "receiver_fanout_30min": 0.0
      },
      "scam_type_actual": "account_takeover",
      "ai_case_summary": {
        "risk_level": "HIGH",
        "scam_type_guess": "social_engineering",
        "summary": "Transaction T0096830 flagged as HIGH RISK (score 100%), most consistent with a scam-call style transfer (large, one-off payment to a brand-new recipient). Evidence: the sender has never sent money to this recipient before; the amount is 3.4x the sender's usual transfer size; the sender made 4 other transactions in the preceding 10 minutes (rapid-fire pattern); the receiving wallet has no transaction history before this. Recommend holding this transaction for manual review before release.",
        "recommendation": "Recommend holding this transaction for manual review before release.",
        "evidence_used": {
          "features": {
            "amount": 9392.3,
            "is_new_recipient": 1.0,
            "amount_vs_avg_ratio": 3.3693415022746147,
            "amount_zscore": 3.524019742323913,
            "unusual_hour": 0.0,
            "sender_velocity_10min": 4.0,
            "new_device_for_sender": 0.0,
            "receiver_age_days": 0.0,
            "receiver_indegree_1h": 0.0,
            "receiver_fanout_30min": 0.0
          },
          "mule_evidence": null
        }
      },
      "mule_network_evidence": null
    },
    {
      "txn_id": "T0096851",
      "timestamp": "2026-08-21 00:02:00",
      "sender_id": "U00538",
      "receiver_id": "Mfe7ada",
      "channel": "send_money",
      "amount": 12098.77,
      "sender_district": "Narayanganj",
      "risk_score": 0.9999999992021352,
      "risk_level": "high",
      "features": {
        "amount": 12098.77,
        "is_new_recipient": 1.0,
        "amount_vs_avg_ratio": 3.9541556120751737,
        "amount_zscore": 6.241833359417996,
        "unusual_hour": 1.0,
        "sender_velocity_10min": 1.0,
        "new_device_for_sender": 0.0,
        "receiver_age_days": 0.0,
        "receiver_indegree_1h": 0.0,
        "receiver_fanout_30min": 0.0
      },
      "scam_type_actual": "account_takeover",
      "ai_case_summary": {
        "risk_level": "HIGH",
        "scam_type_guess": "social_engineering",
        "summary": "Transaction T0096851 flagged as HIGH RISK (score 100%), most consistent with a scam-call style transfer (large, one-off payment to a brand-new recipient). Evidence: the sender has never sent money to this recipient before; the amount is 4.0x the sender's usual transfer size; it happened late at night (11pm-5am), outside typical hours; the receiving wallet has no transaction history before this. Recommend holding this transaction for manual review before release.",
        "recommendation": "Recommend holding this transaction for manual review before release.",
        "evidence_used": {
          "features": {
            "amount": 12098.77,
            "is_new_recipient": 1.0,
            "amount_vs_avg_ratio": 3.9541556120751737,
            "amount_zscore": 6.241833359417996,
            "unusual_hour": 1.0,
            "sender_velocity_10min": 1.0,
            "new_device_for_sender": 0.0,
            "receiver_age_days": 0.0,
            "receiver_indegree_1h": 0.0,
            "receiver_fanout_30min": 0.0
          },
          "mule_evidence": null
        }
      },
      "mule_network_evidence": null
    },
    {
      "txn_id": "T0096818",
      "timestamp": "2026-08-12 10:04:00",
      "sender_id": "U01602",
      "receiver_id": "M1c0f87",
      "channel": "send_money",
      "amount": 18068.39,
      "sender_district": "Narayanganj",
      "risk_score": 0.9999999990974844,
      "risk_level": "high",
      "features": {
        "amount": 18068.39,
        "is_new_recipient": 1.0,
        "amount_vs_avg_ratio": 3.107041351578524,
        "amount_zscore": 2.4459564696608496,
        "unusual_hour": 0.0,
        "sender_velocity_10min": 2.0,
        "new_device_for_sender": 0.0,
        "receiver_age_days": 0.0,
        "receiver_indegree_1h": 0.0,
        "receiver_fanout_30min": 0.0
      },
      "scam_type_actual": "account_takeover",
      "ai_case_summary": {
        "risk_level": "HIGH",
        "scam_type_guess": "social_engineering",
        "summary": "Transaction T0096818 flagged as HIGH RISK (score 100%), most consistent with a scam-call style transfer (large, one-off payment to a brand-new recipient). Evidence: the sender has never sent money to this recipient before; the amount is 3.1x the sender's usual transfer size; the sender made 2 other transactions in the preceding 10 minutes (rapid-fire pattern); the receiving wallet has no transaction history before this. Recommend holding this transaction for manual review before release.",
        "recommendation": "Recommend holding this transaction for manual review before release.",
        "evidence_used": {
          "features": {
            "amount": 18068.39,
            "is_new_recipient": 1.0,
            "amount_vs_avg_ratio": 3.107041351578524,
            "amount_zscore": 2.4459564696608496,
            "unusual_hour": 0.0,
            "sender_velocity_10min": 2.0,
            "new_device_for_sender": 0.0,
            "receiver_age_days": 0.0,
            "receiver_indegree_1h": 0.0,
            "receiver_fanout_30min": 0.0
          },
          "mule_evidence": null
        }
      },
      "mule_network_evidence": null
    },
    {
      "txn_id": "T0096846",
      "timestamp": "2026-09-24 13:08:00",
      "sender_id": "U01945",
      "receiver_id": "M00fda0",
      "channel": "send_money",
      "amount": 18690.94,
      "sender_district": "Narayanganj",
      "risk_score": 0.999999999057311,
      "risk_level": "high",
      "features": {
        "amount": 18690.94,
        "is_new_recipient": 1.0,
        "amount_vs_avg_ratio": 3.7823459995813455,
        "amount_zscore": 6.261512421036596,
        "unusual_hour": 0.0,
        "sender_velocity_10min": 2.0,
        "new_device_for_sender": 0.0,
        "receiver_age_days": 0.0,
        "receiver_indegree_1h": 0.0,
        "receiver_fanout_30min": 0.0
      },
      "scam_type_actual": "account_takeover",
      "ai_case_summary": {
        "risk_level": "HIGH",
        "scam_type_guess": "social_engineering",
        "summary": "Transaction T0096846 flagged as HIGH RISK (score 100%), most consistent with a scam-call style transfer (large, one-off payment to a brand-new recipient). Evidence: the sender has never sent money to this recipient before; the amount is 3.8x the sender's usual transfer size; the sender made 2 other transactions in the preceding 10 minutes (rapid-fire pattern); the receiving wallet has no transaction history before this. Recommend holding this transaction for manual review before release.",
        "recommendation": "Recommend holding this transaction for manual review before release.",
        "evidence_used": {
          "features": {
            "amount": 18690.94,
            "is_new_recipient": 1.0,
            "amount_vs_avg_ratio": 3.7823459995813455,
            "amount_zscore": 6.261512421036596,
            "unusual_hour": 0.0,
            "sender_velocity_10min": 2.0,
            "new_device_for_sender": 0.0,
            "receiver_age_days": 0.0,
            "receiver_indegree_1h": 0.0,
            "receiver_fanout_30min": 0.0
          },
          "mule_evidence": null
        }
      },
      "mule_network_evidence": null
    },
    {
      "txn_id": "T0096853",
      "timestamp": "2026-08-21 00:09:00",
      "sender_id": "U00538",
      "receiver_id": "M0b83bb",
      "channel": "send_money",
      "amount": 12951.2,
      "sender_district": "Sylhet",
      "risk_score": 0.999999999027288,
      "risk_level": "high",
      "features": {
        "amount": 12951.2,
        "is_new_recipient": 1.0,
        "amount_vs_avg_ratio": 2.698862549853541,
        "amount_zscore": 2.044588699101187,
        "unusual_hour": 1.0,
        "sender_velocity_10min": 4.0,
        "new_device_for_sender": 0.0,
        "receiver_age_days": 0.0,
        "receiver_indegree_1h": 0.0,
        "receiver_fanout_30min": 0.0
      },
      "scam_type_actual": "account_takeover",
      "ai_case_summary": {
        "risk_level": "HIGH",
        "scam_type_guess": "unknown",
        "summary": "Transaction T0096853 flagged as HIGH RISK (score 100%), most consistent with an unusual transaction. Evidence: the sender has never sent money to this recipient before; it happened late at night (11pm-5am), outside typical hours; the sender made 4 other transactions in the preceding 10 minutes (rapid-fire pattern); the receiving wallet has no transaction history before this. Recommend holding this transaction for manual review before release.",
        "recommendation": "Recommend holding this transaction for manual review before release.",
        "evidence_used": {
          "features": {
            "amount": 12951.2,
            "is_new_recipient": 1.0,
            "amount_vs_avg_ratio": 2.698862549853541,
            "amount_zscore": 2.044588699101187,
            "unusual_hour": 1.0,
            "sender_velocity_10min": 4.0,
            "new_device_for_sender": 0.0,
            "receiver_age_days": 0.0,
            "receiver_indegree_1h": 0.0,
            "receiver_fanout_30min": 0.0
          },
          "mule_evidence": null
        }
      },
      "mule_network_evidence": null
    },
    {
      "txn_id": "T0096849",
      "timestamp": "2026-09-24 13:10:00",
      "sender_id": "U01945",
      "receiver_id": "Me94dea",
      "channel": "send_money",
      "amount": 19211.52,
      "sender_district": "Chattogram",
      "risk_score": 0.9999999990140592,
      "risk_level": "high",
      "features": {
        "amount": 19211.52,
        "is_new_recipient": 1.0,
        "amount_vs_avg_ratio": 3.2971967749563302,
        "amount_zscore": 3.1432819408463986,
        "unusual_hour": 0.0,
        "sender_velocity_10min": 4.0,
        "new_device_for_sender": 0.0,
        "receiver_age_days": 0.0,
        "receiver_indegree_1h": 0.0,
        "receiver_fanout_30min": 0.0
      },
      "scam_type_actual": "account_takeover",
      "ai_case_summary": {
        "risk_level": "HIGH",
        "scam_type_guess": "social_engineering",
        "summary": "Transaction T0096849 flagged as HIGH RISK (score 100%), most consistent with a scam-call style transfer (large, one-off payment to a brand-new recipient). Evidence: the sender has never sent money to this recipient before; the amount is 3.3x the sender's usual transfer size; the sender made 4 other transactions in the preceding 10 minutes (rapid-fire pattern); the receiving wallet has no transaction history before this. Recommend holding this transaction for manual review before release.",
        "recommendation": "Recommend holding this transaction for manual review before release.",
        "evidence_used": {
          "features": {
            "amount": 19211.52,
            "is_new_recipient": 1.0,
            "amount_vs_avg_ratio": 3.2971967749563302,
            "amount_zscore": 3.1432819408463986,
            "unusual_hour": 0.0,
            "sender_velocity_10min": 4.0,
            "new_device_for_sender": 0.0,
            "receiver_age_days": 0.0,
            "receiver_indegree_1h": 0.0,
            "receiver_fanout_30min": 0.0
          },
          "mule_evidence": null
        }
      },
      "mule_network_evidence": null
    },
    {
      "txn_id": "T0096717",
      "timestamp": "2026-08-12 04:01:00",
      "sender_id": "U00557",
      "receiver_id": "M86ee8e",
      "channel": "send_money",
      "amount": 12710.85,
      "sender_district": "Dhaka",
      "risk_score": 0.9999999989115588,
      "risk_level": "high",
      "features": {
        "amount": 12710.85,
        "is_new_recipient": 1.0,
        "amount_vs_avg_ratio": 4.545690793296956,
        "amount_zscore": 4.069060933921636,
        "unusual_hour": 1.0,
        "sender_velocity_10min": 1.0,
        "new_device_for_sender": 0.0,
        "receiver_age_days": 0.0,
        "receiver_indegree_1h": 0.0,
        "receiver_fanout_30min": 0.0
      },
      "scam_type_actual": "account_takeover",
      "ai_case_summary": {
        "risk_level": "HIGH",
        "scam_type_guess": "social_engineering",
        "summary": "Transaction T0096717 flagged as HIGH RISK (score 100%), most consistent with a scam-call style transfer (large, one-off payment to a brand-new recipient). Evidence: the sender has never sent money to this recipient before; the amount is 4.5x the sender's usual transfer size; it happened late at night (11pm-5am), outside typical hours; the receiving wallet has no transaction history before this. Recommend holding this transaction for manual review before release.",
        "recommendation": "Recommend holding this transaction for manual review before release.",
        "evidence_used": {
          "features": {
            "amount": 12710.85,
            "is_new_recipient": 1.0,
            "amount_vs_avg_ratio": 4.545690793296956,
            "amount_zscore": 4.069060933921636,
            "unusual_hour": 1.0,
            "sender_velocity_10min": 1.0,
            "new_device_for_sender": 0.0,
            "receiver_age_days": 0.0,
            "receiver_indegree_1h": 0.0,
            "receiver_fanout_30min": 0.0
          },
          "mule_evidence": null
        }
      },
      "mule_network_evidence": null
    },
    {
      "txn_id": "T0096795",
      "timestamp": "2026-08-26 01:04:00",
      "sender_id": "U00581",
      "receiver_id": "M2bc3e6",
      "channel": "send_money",
      "amount": 5904.14,
      "sender_district": "Sylhet",
      "risk_score": 0.9999999988583012,
      "risk_level": "high",
      "features": {
        "amount": 5904.14,
        "is_new_recipient": 1.0,
        "amount_vs_avg_ratio": 4.4019414606638,
        "amount_zscore": 7.483383581929824,
        "unusual_hour": 1.0,
        "sender_velocity_10min": 1.0,
        "new_device_for_sender": 0.0,
        "receiver_age_days": 0.0,
        "receiver_indegree_1h": 0.0,
        "receiver_fanout_30min": 0.0
      },
      "scam_type_actual": "account_takeover",
      "ai_case_summary": {
        "risk_level": "HIGH",
        "scam_type_guess": "social_engineering",
        "summary": "Transaction T0096795 flagged as HIGH RISK (score 100%), most consistent with a scam-call style transfer (large, one-off payment to a brand-new recipient). Evidence: the sender has never sent money to this recipient before; the amount is 4.4x the sender's usual transfer size; it happened late at night (11pm-5am), outside typical hours; the receiving wallet has no transaction history before this. Recommend holding this transaction for manual review before release.",
        "recommendation": "Recommend holding this transaction for manual review before release.",
        "evidence_used": {
          "features": {
            "amount": 5904.14,
            "is_new_recipient": 1.0,
            "amount_vs_avg_ratio": 4.4019414606638,
            "amount_zscore": 7.483383581929824,
            "unusual_hour": 1.0,
            "sender_velocity_10min": 1.0,
            "new_device_for_sender": 0.0,
            "receiver_age_days": 0.0,
            "receiver_indegree_1h": 0.0,
            "receiver_fanout_30min": 0.0
          },
          "mule_evidence": null
        }
      },
      "mule_network_evidence": null
    },
    {
      "txn_id": "T0096791",
      "timestamp": "2026-08-14 18:04:00",
      "sender_id": "U01148",
      "receiver_id": "Mca6634",
      "channel": "send_money",
      "amount": 13007.75,
      "sender_district": "Rajshahi",
      "risk_score": 0.9999999987527652,
      "risk_level": "high",
      "features": {
        "amount": 13007.75,
        "is_new_recipient": 1.0,
        "amount_vs_avg_ratio": 3.3789391516902163,
        "amount_zscore": 2.782704364207285,
        "unusual_hour": 0.0,
        "sender_velocity_10min": 3.0,
        "new_device_for_sender": 0.0,
        "receiver_age_days": 0.0,
        "receiver_indegree_1h": 0.0,
        "receiver_fanout_30min": 0.0
      },
      "scam_type_actual": "account_takeover",
      "ai_case_summary": {
        "risk_level": "HIGH",
        "scam_type_guess": "social_engineering",
        "summary": "Transaction T0096791 flagged as HIGH RISK (score 100%), most consistent with a scam-call style transfer (large, one-off payment to a brand-new recipient). Evidence: the sender has never sent money to this recipient before; the amount is 3.4x the sender's usual transfer size; the sender made 3 other transactions in the preceding 10 minutes (rapid-fire pattern); the receiving wallet has no transaction history before this. Recommend holding this transaction for manual review before release.",
        "recommendation": "Recommend holding this transaction for manual review before release.",
        "evidence_used": {
          "features": {
            "amount": 13007.75,
            "is_new_recipient": 1.0,
            "amount_vs_avg_ratio": 3.3789391516902163,
            "amount_zscore": 2.782704364207285,
            "unusual_hour": 0.0,
            "sender_velocity_10min": 3.0,
            "new_device_for_sender": 0.0,
            "receiver_age_days": 0.0,
            "receiver_indegree_1h": 0.0,
            "receiver_fanout_30min": 0.0
          },
          "mule_evidence": null
        }
      },
      "mule_network_evidence": null
    },
    {
      "txn_id": "T0096740",
      "timestamp": "2026-08-08 03:03:00",
      "sender_id": "U01867",
      "receiver_id": "Me26ed9",
      "channel": "send_money",
      "amount": 1387.42,
      "sender_district": "Comilla",
      "risk_score": 0.9999999987008068,
      "risk_level": "high",
      "features": {
        "amount": 1387.42,
        "is_new_recipient": 1.0,
        "amount_vs_avg_ratio": 3.446092960871653,
        "amount_zscore": 2.925552899581031,
        "unusual_hour": 1.0,
        "sender_velocity_10min": 1.0,
        "new_device_for_sender": 0.0,
        "receiver_age_days": 0.0,
        "receiver_indegree_1h": 0.0,
        "receiver_fanout_30min": 0.0
      },
      "scam_type_actual": "account_takeover",
      "ai_case_summary": {
        "risk_level": "HIGH",
        "scam_type_guess": "social_engineering",
        "summary": "Transaction T0096740 flagged as HIGH RISK (score 100%), most consistent with a scam-call style transfer (large, one-off payment to a brand-new recipient). Evidence: the sender has never sent money to this recipient before; the amount is 3.4x the sender's usual transfer size; it happened late at night (11pm-5am), outside typical hours; the receiving wallet has no transaction history before this. Recommend holding this transaction for manual review before release.",
        "recommendation": "Recommend holding this transaction for manual review before release.",
        "evidence_used": {
          "features": {
            "amount": 1387.42,
            "is_new_recipient": 1.0,
            "amount_vs_avg_ratio": 3.446092960871653,
            "amount_zscore": 2.925552899581031,
            "unusual_hour": 1.0,
            "sender_velocity_10min": 1.0,
            "new_device_for_sender": 0.0,
            "receiver_age_days": 0.0,
            "receiver_indegree_1h": 0.0,
            "receiver_fanout_30min": 0.0
          },
          "mule_evidence": null
        }
      },
      "mule_network_evidence": null
    },
    {
      "txn_id": "T0096718",
      "timestamp": "2026-08-12 04:06:00",
      "sender_id": "U00557",
      "receiver_id": "M293cc3",
      "channel": "send_money",
      "amount": 12435.03,
      "sender_district": "Mymensingh",
      "risk_score": 0.9999999987000135,
      "risk_level": "high",
      "features": {
        "amount": 12435.03,
        "is_new_recipient": 1.0,
        "amount_vs_avg_ratio": 2.9781461157859503,
        "amount_zscore": 2.032672326794206,
        "unusual_hour": 1.0,
        "sender_velocity_10min": 3.0,
        "new_device_for_sender": 0.0,
        "receiver_age_days": 0.0,
        "receiver_indegree_1h": 0.0,
        "receiver_fanout_30min": 0.0
      },
      "scam_type_actual": "account_takeover",
      "ai_case_summary": {
        "risk_level": "HIGH",
        "scam_type_guess": "unknown",
        "summary": "Transaction T0096718 flagged as HIGH RISK (score 100%), most consistent with an unusual transaction. Evidence: the sender has never sent money to this recipient before; it happened late at night (11pm-5am), outside typical hours; the sender made 3 other transactions in the preceding 10 minutes (rapid-fire pattern); the receiving wallet has no transaction history before this. Recommend holding this transaction for manual review before release.",
        "recommendation": "Recommend holding this transaction for manual review before release.",
        "evidence_used": {
          "features": {
            "amount": 12435.03,
            "is_new_recipient": 1.0,
            "amount_vs_avg_ratio": 2.9781461157859503,
            "amount_zscore": 2.032672326794206,
            "unusual_hour": 1.0,
            "sender_velocity_10min": 3.0,
            "new_device_for_sender": 0.0,
            "receiver_age_days": 0.0,
            "receiver_indegree_1h": 0.0,
            "receiver_fanout_30min": 0.0
          },
          "mule_evidence": null
        }
      },
      "mule_network_evidence": null
    },
    {
      "txn_id": "T0054001",
      "timestamp": "2026-09-03 07:16:00",
      "sender_id": "A0083",
      "receiver_id": "U00835",
      "channel": "cash_in",
      "amount": 11683.57,
      "sender_district": "Khulna",
      "risk_score": 0.9999999986406952,
      "risk_level": "high",
      "features": {
        "amount": 11683.57,
        "is_new_recipient": 1.0,
        "amount_vs_avg_ratio": 8.20550331139781,
        "amount_zscore": 6.761875200368474,
        "unusual_hour": 0.0,
        "sender_velocity_10min": 0.0,
        "new_device_for_sender": 1.0,
        "receiver_age_days": 3.0,
        "receiver_indegree_1h": 0.0,
        "receiver_fanout_30min": 0.0
      },
      "scam_type_actual": "none",
      "ai_case_summary": {
        "risk_level": "HIGH",
        "scam_type_guess": "social_engineering",
        "summary": "Transaction T0054001 flagged as HIGH RISK (score 100%), most consistent with a scam-call style transfer (large, one-off payment to a brand-new recipient). Evidence: the sender has never sent money to this recipient before; the amount is 8.2x the sender's usual transfer size; it came from a device not previously associated with this sender. Recommend holding this transaction for manual review before release.",
        "recommendation": "Recommend holding this transaction for manual review before release.",
        "evidence_used": {
          "features": {
            "amount": 11683.57,
            "is_new_recipient": 1.0,
            "amount_vs_avg_ratio": 8.20550331139781,
            "amount_zscore": 6.761875200368474,
            "unusual_hour": 0.0,
            "sender_velocity_10min": 0.0,
            "new_device_for_sender": 1.0,
            "receiver_age_days": 3.0,
            "receiver_indegree_1h": 0.0,
            "receiver_fanout_30min": 0.0
          },
          "mule_evidence": null
        }
      },
      "mule_network_evidence": null
    },
    {
      "txn_id": "T0096721",
      "timestamp": "2026-09-01 00:03:00",
      "sender_id": "U00871",
      "receiver_id": "Me1c7e8",
      "channel": "send_money",
      "amount": 12513.09,
      "sender_district": "Sylhet",
      "risk_score": 0.9999999985417104,
      "risk_level": "high",
      "features": {
        "amount": 12513.09,
        "is_new_recipient": 1.0,
        "amount_vs_avg_ratio": 2.8851028116465427,
        "amount_zscore": 2.694998536852,
        "unusual_hour": 1.0,
        "sender_velocity_10min": 1.0,
        "new_device_for_sender": 0.0,
        "receiver_age_days": 0.0,
        "receiver_indegree_1h": 0.0,
        "receiver_fanout_30min": 0.0
      },
      "scam_type_actual": "account_takeover",
      "ai_case_summary": {
        "risk_level": "HIGH",
        "scam_type_guess": "unknown",
        "summary": "Transaction T0096721 flagged as HIGH RISK (score 100%), most consistent with an unusual transaction. Evidence: the sender has never sent money to this recipient before; it happened late at night (11pm-5am), outside typical hours; the receiving wallet has no transaction history before this. Recommend holding this transaction for manual review before release.",
        "recommendation": "Recommend holding this transaction for manual review before release.",
        "evidence_used": {
          "features": {
            "amount": 12513.09,
            "is_new_recipient": 1.0,
            "amount_vs_avg_ratio": 2.8851028116465427,
            "amount_zscore": 2.694998536852,
            "unusual_hour": 1.0,
            "sender_velocity_10min": 1.0,
            "new_device_for_sender": 0.0,
            "receiver_age_days": 0.0,
            "receiver_indegree_1h": 0.0,
            "receiver_fanout_30min": 0.0
          },
          "mule_evidence": null
        }
      },
      "mule_network_evidence": null
    },
    {
      "txn_id": "T0096733",
      "timestamp": "2026-09-01 04:12:00",
      "sender_id": "U00891",
      "receiver_id": "Ma70f01",
      "channel": "send_money",
      "amount": 4114.27,
      "sender_district": "Barishal",
      "risk_score": 0.9999999985248956,
      "risk_level": "high",
      "features": {
        "amount": 4114.27,
        "is_new_recipient": 1.0,
        "amount_vs_avg_ratio": 3.0372834559566515,
        "amount_zscore": 2.7247935533869323,
        "unusual_hour": 1.0,
        "sender_velocity_10min": 3.0,
        "new_device_for_sender": 0.0,
        "receiver_age_days": 0.0,
        "receiver_indegree_1h": 0.0,
        "receiver_fanout_30min": 0.0
      },
      "scam_type_actual": "account_takeover",
      "ai_case_summary": {
        "risk_level": "HIGH",
        "scam_type_guess": "social_engineering",
        "summary": "Transaction T0096733 flagged as HIGH RISK (score 100%), most consistent with a scam-call style transfer (large, one-off payment to a brand-new recipient). Evidence: the sender has never sent money to this recipient before; the amount is 3.0x the sender's usual transfer size; it happened late at night (11pm-5am), outside typical hours; the sender made 3 other transactions in the preceding 10 minutes (rapid-fire pattern); the receiving wallet has no transaction history before this. Recommend holding this transaction for manual review before release.",
        "recommendation": "Recommend holding this transaction for manual review before release.",
        "evidence_used": {
          "features": {
            "amount": 4114.27,
            "is_new_recipient": 1.0,
            "amount_vs_avg_ratio": 3.0372834559566515,
            "amount_zscore": 2.7247935533869323,
            "unusual_hour": 1.0,
            "sender_velocity_10min": 3.0,
            "new_device_for_sender": 0.0,
            "receiver_age_days": 0.0,
            "receiver_indegree_1h": 0.0,
            "receiver_fanout_30min": 0.0
          },
          "mule_evidence": null
        }
      },
      "mule_network_evidence": null
    },
    {
      "txn_id": "T0096941",
      "timestamp": "2026-09-10 03:09:00",
      "sender_id": "U01366",
      "receiver_id": "Mddc2b3",
      "channel": "send_money",
      "amount": 6948.3,
      "sender_district": "Sylhet",
      "risk_score": 0.9999999984495258,
      "risk_level": "high",
      "features": {
        "amount": 6948.3,
        "is_new_recipient": 1.0,
        "amount_vs_avg_ratio": 2.55922302813856,
        "amount_zscore": 1.3462529315317109,
        "unusual_hour": 1.0,
        "sender_velocity_10min": 4.0,
        "new_device_for_sender": 0.0,
        "receiver_age_days": 0.0,
        "receiver_indegree_1h": 0.0,
        "receiver_fanout_30min": 0.0
      },
      "scam_type_actual": "account_takeover",
      "ai_case_summary": {
        "risk_level": "HIGH",
        "scam_type_guess": "unknown",
        "summary": "Transaction T0096941 flagged as HIGH RISK (score 100%), most consistent with an unusual transaction. Evidence: the sender has never sent money to this recipient before; it happened late at night (11pm-5am), outside typical hours; the sender made 4 other transactions in the preceding 10 minutes (rapid-fire pattern); the receiving wallet has no transaction history before this. Recommend holding this transaction for manual review before release.",
        "recommendation": "Recommend holding this transaction for manual review before release.",
        "evidence_used": {
          "features": {
            "amount": 6948.3,
            "is_new_recipient": 1.0,
            "amount_vs_avg_ratio": 2.55922302813856,
            "amount_zscore": 1.3462529315317109,
            "unusual_hour": 1.0,
            "sender_velocity_10min": 4.0,
            "new_device_for_sender": 0.0,
            "receiver_age_days": 0.0,
            "receiver_indegree_1h": 0.0,
            "receiver_fanout_30min": 0.0
          },
          "mule_evidence": null
        }
      },
      "mule_network_evidence": null
    },
    {
      "txn_id": "T0096758",
      "timestamp": "2026-08-05 05:01:00",
      "sender_id": "U01896",
      "receiver_id": "Ma0707c",
      "channel": "send_money",
      "amount": 1517.19,
      "sender_district": "Barishal",
      "risk_score": 0.9999999983217902,
      "risk_level": "high",
      "features": {
        "amount": 1517.19,
        "is_new_recipient": 1.0,
        "amount_vs_avg_ratio": 2.539910268858607,
        "amount_zscore": 1.6985811464827234,
        "unusual_hour": 1.0,
        "sender_velocity_10min": 1.0,
        "new_device_for_sender": 0.0,
        "receiver_age_days": 0.0,
        "receiver_indegree_1h": 0.0,
        "receiver_fanout_30min": 0.0
      },
      "scam_type_actual": "account_takeover",
      "ai_case_summary": {
        "risk_level": "HIGH",
        "scam_type_guess": "unknown",
        "summary": "Transaction T0096758 flagged as HIGH RISK (score 100%), most consistent with an unusual transaction. Evidence: the sender has never sent money to this recipient before; it happened late at night (11pm-5am), outside typical hours; the receiving wallet has no transaction history before this. Recommend holding this transaction for manual review before release.",
        "recommendation": "Recommend holding this transaction for manual review before release.",
        "evidence_used": {
          "features": {
            "amount": 1517.19,
            "is_new_recipient": 1.0,
            "amount_vs_avg_ratio": 2.539910268858607,
            "amount_zscore": 1.6985811464827234,
            "unusual_hour": 1.0,
            "sender_velocity_10min": 1.0,
            "new_device_for_sender": 0.0,
            "receiver_age_days": 0.0,
            "receiver_indegree_1h": 0.0,
            "receiver_fanout_30min": 0.0
          },
          "mule_evidence": null
        }
      },
      "mule_network_evidence": null
    },
    {
      "txn_id": "T0096918",
      "timestamp": "2026-09-24 10:08:00",
      "sender_id": "U01006",
      "receiver_id": "Ma03687",
      "channel": "send_money",
      "amount": 13297.03,
      "sender_district": "Dhaka",
      "risk_score": 0.9999999980245762,
      "risk_level": "high",
      "features": {
        "amount": 13297.03,
        "is_new_recipient": 1.0,
        "amount_vs_avg_ratio": 3.839879913858999,
        "amount_zscore": 4.315661886413723,
        "unusual_hour": 0.0,
        "sender_velocity_10min": 2.0,
        "new_device_for_sender": 0.0,
        "receiver_age_days": 0.0,
        "receiver_indegree_1h": 0.0,
        "receiver_fanout_30min": 0.0
      },
      "scam_type_actual": "account_takeover",
      "ai_case_summary": {
        "risk_level": "HIGH",
        "scam_type_guess": "social_engineering",
        "summary": "Transaction T0096918 flagged as HIGH RISK (score 100%), most consistent with a scam-call style transfer (large, one-off payment to a brand-new recipient). Evidence: the sender has never sent money to this recipient before; the amount is 3.8x the sender's usual transfer size; the sender made 2 other transactions in the preceding 10 minutes (rapid-fire pattern); the receiving wallet has no transaction history before this. Recommend holding this transaction for manual review before release.",
        "recommendation": "Recommend holding this transaction for manual review before release.",
        "evidence_used": {
          "features": {
            "amount": 13297.03,
            "is_new_recipient": 1.0,
            "amount_vs_avg_ratio": 3.839879913858999,
            "amount_zscore": 4.315661886413723,
            "unusual_hour": 0.0,
            "sender_velocity_10min": 2.0,
            "new_device_for_sender": 0.0,
            "receiver_age_days": 0.0,
            "receiver_indegree_1h": 0.0,
            "receiver_fanout_30min": 0.0
          },
          "mule_evidence": null
        }
      },
      "mule_network_evidence": null
    },
    {
      "txn_id": "T0096732",
      "timestamp": "2026-09-01 04:02:00",
      "sender_id": "U00891",
      "receiver_id": "Mb31fe4",
      "channel": "send_money",
      "amount": 5153.37,
      "sender_district": "Rajshahi",
      "risk_score": 0.9999999979586174,
      "risk_level": "high",
      "features": {
        "amount": 5153.37,
        "is_new_recipient": 1.0,
        "amount_vs_avg_ratio": 4.492304875975783,
        "amount_zscore": 6.549055763050454,
        "unusual_hour": 1.0,
        "sender_velocity_10min": 2.0,
        "new_device_for_sender": 0.0,
        "receiver_age_days": 0.0,
        "receiver_indegree_1h": 0.0,
        "receiver_fanout_30min": 0.0
      },
      "scam_type_actual": "account_takeover",
      "ai_case_summary": {
        "risk_level": "HIGH",
        "scam_type_guess": "social_engineering",
        "summary": "Transaction T0096732 flagged as HIGH RISK (score 100%), most consistent with a scam-call style transfer (large, one-off payment to a brand-new recipient). Evidence: the sender has never sent money to this recipient before; the amount is 4.5x the sender's usual transfer size; it happened late at night (11pm-5am), outside typical hours; the sender made 2 other transactions in the preceding 10 minutes (rapid-fire pattern); the receiving wallet has no transaction history before this. Recommend holding this transaction for manual review before release.",
        "recommendation": "Recommend holding this transaction for manual review before release.",
        "evidence_used": {
          "features": {
            "amount": 5153.37,
            "is_new_recipient": 1.0,
            "amount_vs_avg_ratio": 4.492304875975783,
            "amount_zscore": 6.549055763050454,
            "unusual_hour": 1.0,
            "sender_velocity_10min": 2.0,
            "new_device_for_sender": 0.0,
            "receiver_age_days": 0.0,
            "receiver_indegree_1h": 0.0,
            "receiver_fanout_30min": 0.0
          },
          "mule_evidence": null
        }
      },
      "mule_network_evidence": null
    },
    {
      "txn_id": "T0096861",
      "timestamp": "2026-09-03 02:15:00",
      "sender_id": "U01742",
      "receiver_id": "M3d03fc",
      "channel": "send_money",
      "amount": 589.07,
      "sender_district": "Chattogram",
      "risk_score": 0.9999999979452088,
      "risk_level": "high",
      "features": {
        "amount": 589.07,
        "is_new_recipient": 1.0,
        "amount_vs_avg_ratio": 2.4996102849051844,
        "amount_zscore": 1.8683740025373696,
        "unusual_hour": 1.0,
        "sender_velocity_10min": 3.0,
        "new_device_for_sender": 0.0,
        "receiver_age_days": 0.0,
        "receiver_indegree_1h": 0.0,
        "receiver_fanout_30min": 0.0
      },
      "scam_type_actual": "account_takeover",
      "ai_case_summary": {
        "risk_level": "HIGH",
        "scam_type_guess": "unknown",
        "summary": "Transaction T0096861 flagged as HIGH RISK (score 100%), most consistent with an unusual transaction. Evidence: the sender has never sent money to this recipient before; it happened late at night (11pm-5am), outside typical hours; the sender made 3 other transactions in the preceding 10 minutes (rapid-fire pattern); the receiving wallet has no transaction history before this. Recommend holding this transaction for manual review before release.",
        "recommendation": "Recommend holding this transaction for manual review before release.",
        "evidence_used": {
          "features": {
            "amount": 589.07,
            "is_new_recipient": 1.0,
            "amount_vs_avg_ratio": 2.4996102849051844,
            "amount_zscore": 1.8683740025373696,
            "unusual_hour": 1.0,
            "sender_velocity_10min": 3.0,
            "new_device_for_sender": 0.0,
            "receiver_age_days": 0.0,
            "receiver_indegree_1h": 0.0,
            "receiver_fanout_30min": 0.0
          },
          "mule_evidence": null
        }
      },
      "mule_network_evidence": null
    },
    {
      "txn_id": "T0096815",
      "timestamp": "2026-08-06 03:03:00",
      "sender_id": "U01550",
      "receiver_id": "M6c5072",
      "channel": "send_money",
      "amount": 4031.61,
      "sender_district": "Narayanganj",
      "risk_score": 0.9999999979358922,
      "risk_level": "high",
      "features": {
        "amount": 4031.61,
        "is_new_recipient": 1.0,
        "amount_vs_avg_ratio": 3.3446988962880955,
        "amount_zscore": 2.4237902067150485,
        "unusual_hour": 1.0,
        "sender_velocity_10min": 2.0,
        "new_device_for_sender": 0.0,
        "receiver_age_days": 0.0,
        "receiver_indegree_1h": 0.0,
        "receiver_fanout_30min": 0.0
      },
      "scam_type_actual": "account_takeover",
      "ai_case_summary": {
        "risk_level": "HIGH",
        "scam_type_guess": "social_engineering",
        "summary": "Transaction T0096815 flagged as HIGH RISK (score 100%), most consistent with a scam-call style transfer (large, one-off payment to a brand-new recipient). Evidence: the sender has never sent money to this recipient before; the amount is 3.3x the sender's usual transfer size; it happened late at night (11pm-5am), outside typical hours; the sender made 2 other transactions in the preceding 10 minutes (rapid-fire pattern); the receiving wallet has no transaction history before this. Recommend holding this transaction for manual review before release.",
        "recommendation": "Recommend holding this transaction for manual review before release.",
        "evidence_used": {
          "features": {
            "amount": 4031.61,
            "is_new_recipient": 1.0,
            "amount_vs_avg_ratio": 3.3446988962880955,
            "amount_zscore": 2.4237902067150485,
            "unusual_hour": 1.0,
            "sender_velocity_10min": 2.0,
            "new_device_for_sender": 0.0,
            "receiver_age_days": 0.0,
            "receiver_indegree_1h": 0.0,
            "receiver_fanout_30min": 0.0
          },
          "mule_evidence": null
        }
      },
      "mule_network_evidence": null
    },
    {
      "txn_id": "T0096749",
      "timestamp": "2026-09-16 02:12:00",
      "sender_id": "U01798",
      "receiver_id": "M5261eb",
      "channel": "send_money",
      "amount": 25970.63,
      "sender_district": "Narayanganj",
      "risk_score": 0.9999999979295288,
      "risk_level": "high",
      "features": {
        "amount": 25970.63,
        "is_new_recipient": 1.0,
        "amount_vs_avg_ratio": 2.8410915092829128,
        "amount_zscore": 2.279339125757556,
        "unusual_hour": 1.0,
        "sender_velocity_10min": 4.0,
        "new_device_for_sender": 0.0,
        "receiver_age_days": 0.0,
        "receiver_indegree_1h": 0.0,
        "receiver_fanout_30min": 0.0
      },
      "scam_type_actual": "account_takeover",
      "ai_case_summary": {
        "risk_level": "HIGH",
        "scam_type_guess": "unknown",
        "summary": "Transaction T0096749 flagged as HIGH RISK (score 100%), most consistent with an unusual transaction. Evidence: the sender has never sent money to this recipient before; it happened late at night (11pm-5am), outside typical hours; the sender made 4 other transactions in the preceding 10 minutes (rapid-fire pattern); the receiving wallet has no transaction history before this. Recommend holding this transaction for manual review before release.",
        "recommendation": "Recommend holding this transaction for manual review before release.",
        "evidence_used": {
          "features": {
            "amount": 25970.63,
            "is_new_recipient": 1.0,
            "amount_vs_avg_ratio": 2.8410915092829128,
            "amount_zscore": 2.279339125757556,
            "unusual_hour": 1.0,
            "sender_velocity_10min": 4.0,
            "new_device_for_sender": 0.0,
            "receiver_age_days": 0.0,
            "receiver_indegree_1h": 0.0,
            "receiver_fanout_30min": 0.0
          },
          "mule_evidence": null
        }
      },
      "mule_network_evidence": null
    },
    {
      "txn_id": "T0096723",
      "timestamp": "2026-09-01 00:09:00",
      "sender_id": "U00871",
      "receiver_id": "Mbe9c14",
      "channel": "send_money",
      "amount": 13698.0,
      "sender_district": "Chattogram",
      "risk_score": 0.9999999979295288,
      "risk_level": "high",
      "features": {
        "amount": 13698.0,
        "is_new_recipient": 1.0,
        "amount_vs_avg_ratio": 2.8643948532772554,
        "amount_zscore": 2.6509124979997765,
        "unusual_hour": 1.0,
        "sender_velocity_10min": 3.0,
        "new_device_for_sender": 0.0,
        "receiver_age_days": 0.0,
        "receiver_indegree_1h": 0.0,
        "receiver_fanout_30min": 0.0
      },
      "scam_type_actual": "account_takeover",
      "ai_case_summary": {
        "risk_level": "HIGH",
        "scam_type_guess": "unknown",
        "summary": "Transaction T0096723 flagged as HIGH RISK (score 100%), most consistent with an unusual transaction. Evidence: the sender has never sent money to this recipient before; it happened late at night (11pm-5am), outside typical hours; the sender made 3 other transactions in the preceding 10 minutes (rapid-fire pattern); the receiving wallet has no transaction history before this. Recommend holding this transaction for manual review before release.",
        "recommendation": "Recommend holding this transaction for manual review before release.",
        "evidence_used": {
          "features": {
            "amount": 13698.0,
            "is_new_recipient": 1.0,
            "amount_vs_avg_ratio": 2.8643948532772554,
            "amount_zscore": 2.6509124979997765,
            "unusual_hour": 1.0,
            "sender_velocity_10min": 3.0,
            "new_device_for_sender": 0.0,
            "receiver_age_days": 0.0,
            "receiver_indegree_1h": 0.0,
            "receiver_fanout_30min": 0.0
          },
          "mule_evidence": null
        }
      },
      "mule_network_evidence": null
    },
    {
      "txn_id": "T0096847",
      "timestamp": "2026-09-24 13:09:00",
      "sender_id": "U01945",
      "receiver_id": "M5238fd",
      "channel": "send_money",
      "amount": 23052.17,
      "sender_district": "Sylhet",
      "risk_score": 0.999999997828112,
      "risk_level": "high",
      "features": {
        "amount": 23052.17,
        "is_new_recipient": 1.0,
        "amount_vs_avg_ratio": 4.321365976914642,
        "amount_zscore": 5.622289712486597,
        "unusual_hour": 0.0,
        "sender_velocity_10min": 3.0,
        "new_device_for_sender": 0.0,
        "receiver_age_days": 0.0,
        "receiver_indegree_1h": 0.0,
        "receiver_fanout_30min": 0.0
      },
      "scam_type_actual": "account_takeover",
      "ai_case_summary": {
        "risk_level": "HIGH",
        "scam_type_guess": "social_engineering",
        "summary": "Transaction T0096847 flagged as HIGH RISK (score 100%), most consistent with a scam-call style transfer (large, one-off payment to a brand-new recipient). Evidence: the sender has never sent money to this recipient before; the amount is 4.3x the sender's usual transfer size; the sender made 3 other transactions in the preceding 10 minutes (rapid-fire pattern); the receiving wallet has no transaction history before this. Recommend holding this transaction for manual review before release.",
        "recommendation": "Recommend holding this transaction for manual review before release.",
        "evidence_used": {
          "features": {
            "amount": 23052.17,
            "is_new_recipient": 1.0,
            "amount_vs_avg_ratio": 4.321365976914642,
            "amount_zscore": 5.622289712486597,
            "unusual_hour": 0.0,
            "sender_velocity_10min": 3.0,
            "new_device_for_sender": 0.0,
            "receiver_age_days": 0.0,
            "receiver_indegree_1h": 0.0,
            "receiver_fanout_30min": 0.0
          },
          "mule_evidence": null
        }
      },
      "mule_network_evidence": null
    },
    {
      "txn_id": "T0096881",
      "timestamp": "2026-09-17 22:12:00",
      "sender_id": "U00137",
      "receiver_id": "M64fce0",
      "channel": "send_money",
      "amount": 9632.41,
      "sender_district": "Sylhet",
      "risk_score": 0.9999999977401066,
      "risk_level": "high",
      "features": {
        "amount": 9632.41,
        "is_new_recipient": 1.0,
        "amount_vs_avg_ratio": 3.8509543391774153,
        "amount_zscore": 3.6614694312858926,
        "unusual_hour": 0.0,
        "sender_velocity_10min": 3.0,
        "new_device_for_sender": 0.0,
        "receiver_age_days": 0.0,
        "receiver_indegree_1h": 0.0,
        "receiver_fanout_30min": 0.0
      },
      "scam_type_actual": "account_takeover",
      "ai_case_summary": {
        "risk_level": "HIGH",
        "scam_type_guess": "social_engineering",
        "summary": "Transaction T0096881 flagged as HIGH RISK (score 100%), most consistent with a scam-call style transfer (large, one-off payment to a brand-new recipient). Evidence: the sender has never sent money to this recipient before; the amount is 3.9x the sender's usual transfer size; the sender made 3 other transactions in the preceding 10 minutes (rapid-fire pattern); the receiving wallet has no transaction history before this. Recommend holding this transaction for manual review before release.",
        "recommendation": "Recommend holding this transaction for manual review before release.",
        "evidence_used": {
          "features": {
            "amount": 9632.41,
            "is_new_recipient": 1.0,
            "amount_vs_avg_ratio": 3.8509543391774153,
            "amount_zscore": 3.6614694312858926,
            "unusual_hour": 0.0,
            "sender_velocity_10min": 3.0,
            "new_device_for_sender": 0.0,
            "receiver_age_days": 0.0,
            "receiver_indegree_1h": 0.0,
            "receiver_fanout_30min": 0.0
          },
          "mule_evidence": null
        }
      },
      "mule_network_evidence": null
    },
    {
      "txn_id": "T0096973",
      "timestamp": "2026-08-25 12:09:00",
      "sender_id": "U00991",
      "receiver_id": "Mb0f0ea",
      "channel": "send_money",
      "amount": 1495.1,
      "sender_district": "Sylhet",
      "risk_score": 0.9999999970606974,
      "risk_level": "high",
      "features": {
        "amount": 1495.1,
        "is_new_recipient": 1.0,
        "amount_vs_avg_ratio": 3.491800285355165,
        "amount_zscore": 3.6049478261559846,
        "unusual_hour": 0.0,
        "sender_velocity_10min": 4.0,
        "new_device_for_sender": 0.0,
        "receiver_age_days": 0.0,
        "receiver_indegree_1h": 0.0,
        "receiver_fanout_30min": 0.0
      },
      "scam_type_actual": "account_takeover",
      "ai_case_summary": {
        "risk_level": "HIGH",
        "scam_type_guess": "social_engineering",
        "summary": "Transaction T0096973 flagged as HIGH RISK (score 100%), most consistent with a scam-call style transfer (large, one-off payment to a brand-new recipient). Evidence: the sender has never sent money to this recipient before; the amount is 3.5x the sender's usual transfer size; the sender made 4 other transactions in the preceding 10 minutes (rapid-fire pattern); the receiving wallet has no transaction history before this. Recommend holding this transaction for manual review before release.",
        "recommendation": "Recommend holding this transaction for manual review before release.",
        "evidence_used": {
          "features": {
            "amount": 1495.1,
            "is_new_recipient": 1.0,
            "amount_vs_avg_ratio": 3.491800285355165,
            "amount_zscore": 3.6049478261559846,
            "unusual_hour": 0.0,
            "sender_velocity_10min": 4.0,
            "new_device_for_sender": 0.0,
            "receiver_age_days": 0.0,
            "receiver_indegree_1h": 0.0,
            "receiver_fanout_30min": 0.0
          },
          "mule_evidence": null
        }
      },
      "mule_network_evidence": null
    },
    {
      "txn_id": "T0096925",
      "timestamp": "2026-08-05 02:02:00",
      "sender_id": "U00643",
      "receiver_id": "M4d58ae",
      "channel": "send_money",
      "amount": 1321.82,
      "sender_district": "Rajshahi",
      "risk_score": 0.9999999970128142,
      "risk_level": "high",
      "features": {
        "amount": 1321.82,
        "is_new_recipient": 1.0,
        "amount_vs_avg_ratio": 2.7591662926742715,
        "amount_zscore": 1.7034232099724258,
        "unusual_hour": 1.0,
        "sender_velocity_10min": 1.0,
        "new_device_for_sender": 0.0,
        "receiver_age_days": 0.0,
        "receiver_indegree_1h": 0.0,
        "receiver_fanout_30min": 0.0
      },
      "scam_type_actual": "account_takeover",
      "ai_case_summary": {
        "risk_level": "HIGH",
        "scam_type_guess": "unknown",
        "summary": "Transaction T0096925 flagged as HIGH RISK (score 100%), most consistent with an unusual transaction. Evidence: the sender has never sent money to this recipient before; it happened late at night (11pm-5am), outside typical hours; the receiving wallet has no transaction history before this. Recommend holding this transaction for manual review before release.",
        "recommendation": "Recommend holding this transaction for manual review before release.",
        "evidence_used": {
          "features": {
            "amount": 1321.82,
            "is_new_recipient": 1.0,
            "amount_vs_avg_ratio": 2.7591662926742715,
            "amount_zscore": 1.7034232099724258,
            "unusual_hour": 1.0,
            "sender_velocity_10min": 1.0,
            "new_device_for_sender": 0.0,
            "receiver_age_days": 0.0,
            "receiver_indegree_1h": 0.0,
            "receiver_fanout_30min": 0.0
          },
          "mule_evidence": null
        }
      },
      "mule_network_evidence": null
    },
    {
      "txn_id": "T0096819",
      "timestamp": "2026-08-12 10:06:00",
      "sender_id": "U01602",
      "receiver_id": "M9833f3",
      "channel": "send_money",
      "amount": 19983.65,
      "sender_district": "Khulna",
      "risk_score": 0.9999999968965808,
      "risk_level": "high",
      "features": {
        "amount": 19983.65,
        "is_new_recipient": 1.0,
        "amount_vs_avg_ratio": 2.883967802755735,
        "amount_zscore": 2.199633892683968,
        "unusual_hour": 0.0,
        "sender_velocity_10min": 3.0,
        "new_device_for_sender": 0.0,
        "receiver_age_days": 0.0,
        "receiver_indegree_1h": 0.0,
        "receiver_fanout_30min": 0.0
      },
      "scam_type_actual": "account_takeover",
      "ai_case_summary": {
        "risk_level": "HIGH",
        "scam_type_guess": "unknown",
        "summary": "Transaction T0096819 flagged as HIGH RISK (score 100%), most consistent with an unusual transaction. Evidence: the sender has never sent money to this recipient before; the sender made 3 other transactions in the preceding 10 minutes (rapid-fire pattern); the receiving wallet has no transaction history before this. Recommend holding this transaction for manual review before release.",
        "recommendation": "Recommend holding this transaction for manual review before release.",
        "evidence_used": {
          "features": {
            "amount": 19983.65,
            "is_new_recipient": 1.0,
            "amount_vs_avg_ratio": 2.883967802755735,
            "amount_zscore": 2.199633892683968,
            "unusual_hour": 0.0,
            "sender_velocity_10min": 3.0,
            "new_device_for_sender": 0.0,
            "receiver_age_days": 0.0,
            "receiver_indegree_1h": 0.0,
            "receiver_fanout_30min": 0.0
          },
          "mule_evidence": null
        }
      },
      "mule_network_evidence": null
    },
    {
      "txn_id": "T0096813",
      "timestamp": "2026-08-06 03:02:00",
      "sender_id": "U01550",
      "receiver_id": "M28a525",
      "channel": "send_money",
      "amount": 3817.38,
      "sender_district": "Sylhet",
      "risk_score": 0.9999999965167444,
      "risk_level": "high",
      "features": {
        "amount": 3817.38,
        "is_new_recipient": 1.0,
        "amount_vs_avg_ratio": 3.864895671535132,
        "amount_zscore": 3.0566046688579283,
        "unusual_hour": 1.0,
        "sender_velocity_10min": 1.0,
        "new_device_for_sender": 0.0,
        "receiver_age_days": 0.0,
        "receiver_indegree_1h": 0.0,
        "receiver_fanout_30min": 0.0
      },
      "scam_type_actual": "account_takeover",
      "ai_case_summary": {
        "risk_level": "HIGH",
        "scam_type_guess": "social_engineering",
        "summary": "Transaction T0096813 flagged as HIGH RISK (score 100%), most consistent with a scam-call style transfer (large, one-off payment to a brand-new recipient). Evidence: the sender has never sent money to this recipient before; the amount is 3.9x the sender's usual transfer size; it happened late at night (11pm-5am), outside typical hours; the receiving wallet has no transaction history before this. Recommend holding this transaction for manual review before release.",
        "recommendation": "Recommend holding this transaction for manual review before release.",
        "evidence_used": {
          "features": {
            "amount": 3817.38,
            "is_new_recipient": 1.0,
            "amount_vs_avg_ratio": 3.864895671535132,
            "amount_zscore": 3.0566046688579283,
            "unusual_hour": 1.0,
            "sender_velocity_10min": 1.0,
            "new_device_for_sender": 0.0,
            "receiver_age_days": 0.0,
            "receiver_indegree_1h": 0.0,
            "receiver_fanout_30min": 0.0
          },
          "mule_evidence": null
        }
      },
      "mule_network_evidence": null
    }
  ],
  "mule_wallets": [
    {
      "wallet": "Mb4170b",
      "distinct_senders_total": 14,
      "max_distinct_senders_in_1h": 11,
      "total_received": 141929.07,
      "total_sent_out": 137062.23,
      "cash_out_ratio": 0.966,
      "first_seen": "2026-08-31T20:14:00",
      "wallet_age_days": 29.07,
      "pass_through_minutes_after_last_inflow": 26.0,
      "mule_score": 0.85,
      "reasons": [
        "11 distinct senders within a single hour (very high burst)",
        "relatively new wallet (29 days of history)",
        "97% of received funds moved back out within 26 minutes of the last incoming transfer"
      ]
    },
    {
      "wallet": "M3e7fd9",
      "distinct_senders_total": 14,
      "max_distinct_senders_in_1h": 10,
      "total_received": 132911.88,
      "total_sent_out": 125396.16,
      "cash_out_ratio": 0.943,
      "first_seen": "2026-09-02T19:03:00",
      "wallet_age_days": 27.12,
      "pass_through_minutes_after_last_inflow": 26.0,
      "mule_score": 0.85,
      "reasons": [
        "10 distinct senders within a single hour (very high burst)",
        "relatively new wallet (27 days of history)",
        "94% of received funds moved back out within 26 minutes of the last incoming transfer"
      ]
    },
    {
      "wallet": "Ma9f7f0",
      "distinct_senders_total": 14,
      "max_distinct_senders_in_1h": 10,
      "total_received": 139388.12,
      "total_sent_out": 131465.81,
      "cash_out_ratio": 0.943,
      "first_seen": "2026-09-14T14:00:00",
      "wallet_age_days": 15.33,
      "pass_through_minutes_after_last_inflow": 20.0,
      "mule_score": 0.85,
      "reasons": [
        "10 distinct senders within a single hour (very high burst)",
        "relatively new wallet (15 days of history)",
        "94% of received funds moved back out within 20 minutes of the last incoming transfer"
      ]
    },
    {
      "wallet": "M883c63",
      "distinct_senders_total": 14,
      "max_distinct_senders_in_1h": 9,
      "total_received": 147933.12,
      "total_sent_out": 133208.9,
      "cash_out_ratio": 0.9,
      "first_seen": "2026-09-22T09:01:00",
      "wallet_age_days": 7.54,
      "pass_through_minutes_after_last_inflow": 44.0,
      "mule_score": 0.85,
      "reasons": [
        "9 distinct senders within a single hour (very high burst)",
        "relatively new wallet (8 days of history)",
        "90% of received funds moved back out within 44 minutes of the last incoming transfer"
      ]
    },
    {
      "wallet": "Mf7d992",
      "distinct_senders_total": 14,
      "max_distinct_senders_in_1h": 10,
      "total_received": 128149.02,
      "total_sent_out": 109766.23,
      "cash_out_ratio": 0.857,
      "first_seen": "2026-08-23T19:04:00",
      "wallet_age_days": 37.12,
      "pass_through_minutes_after_last_inflow": 24.0,
      "mule_score": 0.75,
      "reasons": [
        "10 distinct senders within a single hour (very high burst)",
        "86% of received funds moved back out within 24 minutes of the last incoming transfer"
      ]
    },
    {
      "wallet": "M70b5bd",
      "distinct_senders_total": 14,
      "max_distinct_senders_in_1h": 11,
      "total_received": 149451.6,
      "total_sent_out": 142852.71,
      "cash_out_ratio": 0.956,
      "first_seen": "2026-08-24T09:09:00",
      "wallet_age_days": 36.53,
      "pass_through_minutes_after_last_inflow": 42.0,
      "mule_score": 0.75,
      "reasons": [
        "11 distinct senders within a single hour (very high burst)",
        "96% of received funds moved back out within 42 minutes of the last incoming transfer"
      ]
    },
    {
      "wallet": "U01141",
      "distinct_senders_total": 21,
      "max_distinct_senders_in_1h": 3,
      "total_received": 42228.33,
      "total_sent_out": 32798.32,
      "cash_out_ratio": 0.777,
      "first_seen": "2026-08-01T14:36:00",
      "wallet_age_days": 59.31,
      "pass_through_minutes_after_last_inflow": 98.0,
      "mule_score": 0.55,
      "reasons": [
        "3 distinct senders within a single hour",
        "78% of received funds moved back out within 98 minutes of the last incoming transfer"
      ]
    },
    {
      "wallet": "U01481",
      "distinct_senders_total": 25,
      "max_distinct_senders_in_1h": 3,
      "total_received": 41990.44,
      "total_sent_out": 54838.24,
      "cash_out_ratio": 1.306,
      "first_seen": "2026-08-02T16:17:00",
      "wallet_age_days": 58.24,
      "pass_through_minutes_after_last_inflow": 169.0,
      "mule_score": 0.55,
      "reasons": [
        "3 distinct senders within a single hour",
        "131% of received funds moved back out within 169 minutes of the last incoming transfer"
      ]
    },
    {
      "wallet": "U00211",
      "distinct_senders_total": 23,
      "max_distinct_senders_in_1h": 3,
      "total_received": 37312.73,
      "total_sent_out": 31106.31,
      "cash_out_ratio": 0.834,
      "first_seen": "2026-08-02T20:32:00",
      "wallet_age_days": 58.06,
      "pass_through_minutes_after_last_inflow": 91.0,
      "mule_score": 0.55,
      "reasons": [
        "3 distinct senders within a single hour",
        "83% of received funds moved back out within 91 minutes of the last incoming transfer"
      ]
    },
    {
      "wallet": "U00093",
      "distinct_senders_total": 26,
      "max_distinct_senders_in_1h": 3,
      "total_received": 58683.61,
      "total_sent_out": 45035.34,
      "cash_out_ratio": 0.767,
      "first_seen": "2026-08-03T09:27:00",
      "wallet_age_days": 57.52,
      "pass_through_minutes_after_last_inflow": 73.0,
      "mule_score": 0.55,
      "reasons": [
        "3 distinct senders within a single hour",
        "77% of received funds moved back out within 73 minutes of the last incoming transfer"
      ]
    },
    {
      "wallet": "U01156",
      "distinct_senders_total": 16,
      "max_distinct_senders_in_1h": 3,
      "total_received": 24649.39,
      "total_sent_out": 47037.81,
      "cash_out_ratio": 1.908,
      "first_seen": "2026-08-03T11:29:00",
      "wallet_age_days": 57.44,
      "pass_through_minutes_after_last_inflow": 178.0,
      "mule_score": 0.55,
      "reasons": [
        "3 distinct senders within a single hour",
        "191% of received funds moved back out within 178 minutes of the last incoming transfer"
      ]
    },
    {
      "wallet": "U01480",
      "distinct_senders_total": 26,
      "max_distinct_senders_in_1h": 3,
      "total_received": 63392.84,
      "total_sent_out": 59440.31,
      "cash_out_ratio": 0.938,
      "first_seen": "2026-08-10T14:59:00",
      "wallet_age_days": 50.29,
      "pass_through_minutes_after_last_inflow": 179.0,
      "mule_score": 0.55,
      "reasons": [
        "3 distinct senders within a single hour",
        "94% of received funds moved back out within 179 minutes of the last incoming transfer"
      ]
    }
  ],
  "mule_clusters": [
    {
      "cluster_id": 0,
      "size": 178,
      "wallets": [
        "A0055",
        "U01319",
        "U01086",
        "U01267",
        "U01423",
        "U01639",
        "A0033",
        "U00109",
        "U01548",
        "U01371",
        "U01461",
        "U00859",
        "U00201",
        "U01380",
        "U00269",
        "U00199",
        "A0113",
        "U01409",
        "U00370",
        "A0104",
        "U01152",
        "U00930",
        "U01869",
        "U01842",
        "U01599"
      ]
    },
    {
      "cluster_id": 1,
      "size": 29,
      "wallets": [
        "U00415",
        "U01860",
        "U00815",
        "U01822",
        "U00372",
        "Mb4170b",
        "U01841",
        "U01126",
        "U00367",
        "U01208",
        "U00486",
        "M883c63",
        "U01590",
        "U00998",
        "U00718",
        "U00444",
        "U01023",
        "U00078",
        "U00882",
        "U01970",
        "U01851",
        "U00573",
        "U01055",
        "U00609",
        "U01025"
      ]
    },
    {
      "cluster_id": 2,
      "size": 15,
      "wallets": [
        "U01383",
        "U01942",
        "U01948",
        "U01463",
        "U01338",
        "U01612",
        "U01065",
        "U01615",
        "M3e7fd9",
        "U00410",
        "U00948",
        "U01396",
        "U00474",
        "U01350",
        "U01487"
      ]
    }
  ]
};
