"""
Generates frontend/demo_data.js - a precomputed snapshot of stats, flagged
transactions (with AI case summaries already attached), and mule network
data. The dashboard loads this directly, so it works perfectly even if
nobody has the Flask API running (e.g. opening the HTML file straight from
a laptop during judging). If the live API IS running, the dashboard prefers
live data and only falls back to this snapshot.
"""

import json
import os
import pandas as pd

from features import FEATURE_COLUMNS
from investigation_assistant import template_explain

HERE = os.path.dirname(__file__)
DATA_DIR = os.path.join(HERE, "..", "..", "data")
FRONTEND_DIR = os.path.join(HERE, "..", "..", "frontend")


def risk_level(score):
    if score >= 0.7:
        return "high"
    if score >= 0.4:
        return "medium"
    return "low"


def main():
    scored_df = pd.read_csv(os.path.join(DATA_DIR, "scored_transactions.csv"))
    with open(os.path.join(DATA_DIR, "mule_report.json")) as f:
        mule_report = json.load(f)
    with open(os.path.join(DATA_DIR, "evaluation.json")) as f:
        evaluation = json.load(f)
    with open(os.path.join(DATA_DIR, "feature_importance.json")) as f:
        feature_importance = json.load(f)

    mule_by_wallet = {w["wallet"]: w for w in mule_report["top_suspicious_wallets"]}

    total = len(scored_df)
    flagged = scored_df[scored_df["risk_score"] >= 0.4]
    high = scored_df[scored_df["risk_score"] >= 0.7]

    stats = {
        "total_transactions": int(total),
        "flagged_medium_plus": int(len(flagged)),
        "flagged_high": int(len(high)),
        "mule_wallets_detected": mule_report["graph_summary"]["flagged_wallets"],
        "suspicious_clusters": len(mule_report["suspicious_clusters"]),
        "model_evaluation": evaluation,
        "feature_importance": feature_importance,
    }

    # top 40 highest-risk transactions, each with full AI case summary attached
    top = scored_df.sort_values("risk_score", ascending=False).head(40)
    transactions = []
    for _, row in top.iterrows():
        feats = {c: float(row[c]) for c in FEATURE_COLUMNS}
        txn = {
            "txn_id": row["txn_id"],
            "timestamp": row["timestamp"],
            "sender_id": row["sender_id"],
            "receiver_id": row["receiver_id"],
            "channel": row["channel"],
            "amount": float(row["amount"]),
            "sender_district": row.get("sender_district"),
            "risk_score": float(row["risk_score"]),
            "risk_level": risk_level(row["risk_score"]),
            "features": feats,
            "scam_type_actual": row.get("scam_type", "none"),  # ground truth, for the demo narrative only
        }
        mule_evidence = mule_by_wallet.get(row["receiver_id"])
        explanation = template_explain(txn, row["risk_score"], [], mule_evidence)
        txn["ai_case_summary"] = explanation
        txn["mule_network_evidence"] = mule_evidence
        transactions.append(txn)

    snapshot = {
        "generated_note": "Precomputed snapshot from the synthetic dataset for offline/standalone demo use.",
        "stats": stats,
        "transactions": transactions,
        "mule_wallets": mule_report["top_suspicious_wallets"],
        "mule_clusters": mule_report["suspicious_clusters"],
    }

    os.makedirs(FRONTEND_DIR, exist_ok=True)
    out_path = os.path.join(FRONTEND_DIR, "demo_data.js")
    with open(out_path, "w") as f:
        f.write("// Auto-generated by generate_demo_snapshot.py - do not edit by hand.\n")
        f.write("const DEMO_DATA = ")
        json.dump(snapshot, f, indent=2)
        f.write(";\n")

    print(f"Wrote demo snapshot ({len(transactions)} transactions) to {out_path}")


if __name__ == "__main__":
    main()
